### ISSUE TITLE
In login-popup, check token validity

### ISSUE THREAD

**Issue by TimvdLippe** [Mentoraat/plannings-tool-client#21]
- [ ] Look up cache for token
- [ ] Post request to end-point of https://github.com/Mentoraat/plannings-tool-server/issues/21
- [ ] If valid, immediately redirect to `<main-panel>`

**Comment by TimvdLippe** [comment]
We might be able to use https://open-elements.org/elements/iron-localstorage for caching

**Comment by TimvdLippe** [comment]
If we are caching, we are forced to notify the user. We can use https://github.com/marcus7777/show-once for this message.

**Comment by TimvdLippe** [comment]
This should be a lot easier now that we have `login-check`

**Comment by GijsWeterings** [comment]
as you mentioned in telegram, we wanna move login to `/` and the main-panel to `/app`
