### ISSUE TITLE
Enable compression in nginx

### ISSUE THREAD

**Issue by TimvdLippe** [Mentoraat/plannings-tool-client#37]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fplanningstool.weaverwebdevelopment.nl%2F&tab=mobile

https://developers.google.com/speed/docs/insights/EnableCompression

http://nginx.org/en/docs/http/ngx_http_gzip_module.html

**Comment by GijsWeterings** [comment]
Done!
For future reference, add the following to `/etc/nginx/nginx.conf`:

```
    gzip on;
    gzip_disable "msie6";

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
```

and restart nginx
