### ISSUE TITLE
Distinguish events from eachother by course

### ISSUE THREAD

**Issue by GijsWeterings** [Mentoraat/plannings-tool-client#8]
Display events in such a way it's clear what event belongs to what course.

**Comment by TimvdLippe** [comment]
In order to do this, we have to show the data of the event in some sort of way. If we want to do this in an attribute (data-event), we would need to change Views in fullCalendar. Currently you have no way to access the data so neither in CSS.

**Comment by TimvdLippe** [comment]
Was fixed in #17 with coloring of events and assignments.
